//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subasta.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subasta.Recursos.MensagensErro", typeof(MensagensErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menores de idade não podem participar de leilões..
        /// </summary>
        public static string ApenasMaioresDeDezoito {
            get {
                return ResourceManager.GetString("ApenasMaioresDeDezoito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe a data de início posterior a data atual..
        /// </summary>
        public static string DataInicioObrigatoria {
            get {
                return ResourceManager.GetString("DataInicioObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe a data de nascimento..
        /// </summary>
        public static string DataNascimentoObrigatoria {
            get {
                return ResourceManager.GetString("DataNascimentoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe a descrição..
        /// </summary>
        public static string DescricaoObrigatoria {
            get {
                return ResourceManager.GetString("DescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe o e-mail..
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O item não foi encontrado..
        /// </summary>
        public static string ItemNaoEncontrado {
            get {
                return ResourceManager.GetString("ItemNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe ao menos um item para o leilão..
        /// </summary>
        public static string ItemObrigatorio {
            get {
                return ResourceManager.GetString("ItemObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, faça um lance com valor superior ao valor mínimo do item..
        /// </summary>
        public static string LanceAbaixoDoValorInicial {
            get {
                return ResourceManager.GetString("LanceAbaixoDoValorInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O leilão não foi encontrado..
        /// </summary>
        public static string LeilaoNaoEncontrado {
            get {
                return ResourceManager.GetString("LeilaoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login escolhido já está em uso..
        /// </summary>
        public static string LoginEstaEmUso {
            get {
                return ResourceManager.GetString("LoginEstaEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe o login..
        /// </summary>
        public static string LoginObrigatorio {
            get {
                return ResourceManager.GetString("LoginObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe o nome..
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe uma senha com no mínimo 6 caracteres, 1 letra maiúscula, 1 letra minúscula e 1 número..
        /// </summary>
        public static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, informe um valor inicial maior que zero..
        /// </summary>
        public static string ValorInicialMaiorQueZero {
            get {
                return ResourceManager.GetString("ValorInicialMaiorQueZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, faça um lance com valor superior ao último feito..
        /// </summary>
        public static string ValorLanceAbaixoDoUltimo {
            get {
                return ResourceManager.GetString("ValorLanceAbaixoDoUltimo", resourceCulture);
            }
        }
    }
}
